# Generated by Django 4.2.6 on 2023-12-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_route_duration_remove_route_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='schedule',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
