# Generated by Django 4.2.6 on 2023-12-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_route_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.AddField(
            model_name='route',
            name='price',
            field=models.CharField(default=None, max_length=6, null=True),
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
    ]
