# Generated by Django 4.2.6 on 2023-12-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_ticket_bus_remove_ticket_price_route_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='purchase_date',
        ),
    ]
