# Generated by Django 4.2.6 on 2023-12-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_route_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='status',
            field=models.CharField(default='Ожидает', max_length=30),
        ),
    ]
