# Generated by Django 4.2.6 on 2023-12-17 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_passenger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bus',
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
    ]
